### ISSUE TITLE
Union keyword should be highlighted

### ISSUE THREAD

**Issue by pierreis** [joshuawarner32/capnproto-sublime#2]
I guess the title is quite self-explanatory... :)
On the current version, **`union`** keyword, part of the language, is not highlighted.

**Comment by joshuawarner32** [comment]
Thanks for reporting this!

I vaguely recall planning on trying to highlight 'union' only in the correct context (i.e. not a top-level type).  Apparently I never got around to that.

This is just the quick-and-simple fix of adding it to the keywords list.
